set(GLEW_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/include")

set(GLEW_LIBRARIES_DIR "${CMAKE_CURRENT_LIST_DIR}/bin/Release/x64/")

set(GLEW_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/Release/x64/glew32.lib")

string(STRIP "${GLEW_LIBRARIES}" GLEW_LIBRARIES)